### ISSUE TITLE
Usage of properies of the parent class is not recognized

### ISSUE THREAD

**Issue by trailsnail** [TomasVotruba/unused-public#102]
Hi,

I have put together a small example where I think I get a false-positive result: 
https://phpstan.org/r/5ee23f4f-e79d-4482-98af-0cdd61da2854

Shouldn't the use of parent properties when accessing via the inheriting classes actually be recognized?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

While technically the property is used, the purpose of this package is to avoid these extended family relations.

Such property should be moved directly to the child class, or used on the abstract type instead.

See for more reasoning:
https://github.com/TomasVotruba/unused-public/pull/98#issuecomment-1946250168
