### ISSUE TITLE
ignore getter/setter methods

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/unused-public#113]
I can see devs spending an enourmous amount of time re-validating whether unused-public really is correct about a certain super simple setter and/or getter method is really unused (because e.g. some framework magic might be involved unused-public cannot know about).

IMO hunting within a codebase for a unused simple getter and/or setter is not worth the time doing so.

what do you think about ignoring trivial setters/getters like

```php
class X {
  public function setY($y) {
    $this->y = $y;
  }
  public function getY() {
    return $this->y;
  }
}
```

?

it could either be a new option or maybe done by default... wdyt?

**Comment by TomasVotruba** [comment]
This actually showed some properties unused as well, as none were used.

This package should be raw as possible. Adding more custom conditions would make it far way from the simple idea.
