### ISSUE TITLE
False positives for test classes

### ISSUE THREAD

**Issue by wimwinterberg** [TomasVotruba/unused-public#124]
Hi,

Great work for this extension. 
I was wondering what the reason is for skipping test classes. I have some reports of unused usages, but in fact they are used in my tests.
This also occurs when for example constants are defined in test class X and used in test class Y.

Btw. I see some reasons why normal code should not have methods, constants which is only used in test code. But I don't understand why test code only cannot have shared constants. Maybe a parameter can be introduced to toggle this behaviour?

Thanks again for your time and work.

Wim

**Comment by ruudk** [comment]
The goal of this repository is to find unused public methods, aka dead code. 

If the tests would be considered as usage for the public methods, then it will find a lot less dead code, as most code always has a test.

**Comment by TomasVotruba** [comment]
As @ruudk writes, code that is only used in tests is not used in public and should be deleted with test.

**Comment by wimwinterberg** [comment]
I agree. But the problem I am running into is that one test class uses a constant value from another test class.
Now I get an report that this const is unused, but infact it is used by another test class.

**Comment by TomasVotruba** [comment]
Not sure we can solve this without negatively affecting the rest.
I'd ignore these errors in config.

**Comment by wimwinterberg** [comment]
Is there a way to ignore these without affecting the percentages?

**Comment by TomasVotruba** [comment]
Not at the moment. Best practice is to avoid percentage, it's useful only for really bad project at the beginning

**Comment by wimwinterberg** [comment]
Oke, thank you for your time and answers.
