### ISSUE TITLE
It seems twig method usage detection does not consider type that it's called on

### ISSUE THREAD

**Issue by simPod** [TomasVotruba/unused-public#129]
I've setup templates path

```neon
# phpstan.neon
parameters:
    unused_public:
        template_paths:
            - templates
```

where I call `name()` on type `A`. It correctly marked `A.name()` as used.

However, it also started to consider `B.name()`, `C.name()` etc. methods as used, even though they're not.

So I have a suspicion that only a method name is considered.

**Comment by TomasVotruba** [comment]
You're correct. This is a feature, as to analyse types, the full controller + templates would have to be parsed. In reality, those types are not known in template and template can be used from many places, e.g. includes etc.
This is to avoid false positives.

**Comment by simPod** [comment]
I thought it would have to be much more complex. Thanks.

**Comment by TomasVotruba** [comment]
@simPod I actually made such a "smart" tool for Twig in past (https://tomasvotruba.com/blog/stamp-1-how-to-compile-twig-to-php), but it yielded so many false positives it added more work than saved time :) that's why I went for this dummy cost-effective approach
