### ISSUE TITLE
False positive on methods defined in abstract classes used in interfaces

### ISSUE THREAD

**Issue by xdanik** [TomasVotruba/unused-public#132]
It seems, that if abstract class defines an method, that is only used because of interface that child classes are implementing, it results in false positive unused method error.

Having following code as an example:

AbstractImport.php:
```
<?php
namespace Demo;

abstract class AbstractImport
{
    public function demoMethod(): void
    {
    }
}
```
Import.php:
```
<?php
namespace Demo;

class Import extends AbstractImport implements ImportInterface
{
}
```
ImportInterface.php:
```
<?php
namespace Demo;

interface ImportInterface
{
    public function demoMethod(): void;
}
```

Some usage:
```
namespace Demo;

/** @var ImportInterface[] $imports */
$imports = [
    new Import(),
];

// generate some usage
foreach ($imports as $import) {
    $import->demoMethod();
}
```

Results in:
```
 ------ -------------------------------------------------------------------
  Line   data/Demo/AbstractImport.php
 ------ -------------------------------------------------------------------
  7      Public method "Demo\AbstractImport::demoMethod()" is never used
         💡 Either reduce visibility or annotate it or its class with @api
 ------ -------------------------------------------------------------------
```

Maybe related to https://github.com/TomasVotruba/unused-public/issues/102 , but not really sure.

**Comment by TomasVotruba** [comment]
This is correct, as `AbstractImport` is never used. It must be imlemented directly, to avoid hacks like these. 

The intent here is that all classes extending `AbstractImport` use `demoMethod()` that is required by the `ImportInterface` interface. There is ho value in a such class:

```php
<?php

namespace Demo;

class Import extends AbstractImport
{
}
``` 

Rule of thumb is to use interface at fist occurence of interface method :+1: 

```php
<?php
namespace Demo;

abstract class AbstractImport implements ImportInterface
{
    public function demoMethod(): void
    {
    }
}
```
