### ISSUE TITLE
Support per folder config

### ISSUE THREAD

**Issue by williamdes** [TomasVotruba/unused-public#133]
With Laravel I get a lot of false positives on scopes and properties
I would like to be able to skip folders or have rules per folder

**Comment by TomasVotruba** [comment]
Can you share failing test case, so I can see what you mean?

**Comment by williamdes** [comment]
> Can you share failing test case, so I can see what you mean?

Sure, I ended up making a horrible script with regexes to find functions etc..
I will share some examples
but for example Laravel has functions on Models that are scopes, for example: `public function scopeConfirmed(Builder $builder): Builder`
It is used like this: `Users::confirmed()->all()`
So obviously this tool will report it as unused not seeing the connection between the two.
There is more of this stuff, let me know what you already feel about the scope function part.

https://laravel.com/docs/11.x/eloquent#local-scopes

**Comment by TomasVotruba** [comment]
I see :) I think magic calls are outside this this tool scope. If any framework calls some method magically, it will be reported as false positive.

Add these cases to `phpstan.neon` and mark as known false positives. That way the rest of project will be detected correctly :+1:

**Comment by williamdes** [comment]
> I see :) I think magic calls are outside this this tool scope. If any framework calls some method magically, it will be reported as false positive.
> 
> Add these cases to `phpstan.neon` and mark as known false positives. That way the rest of project will be detected correctly 👍

Not even needed to add them to the baseline when you have Larastan that understands them 🎉

Thanks for clarifying the scope of this project, that's what I was thinking as it becomes way too tricky

**Comment by TomasVotruba** [comment]
Indeed, Larastan is required, but it doesn't always get all the magic :)
