### ISSUE TITLE
detect cross repository unused methods

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/unused-public#136]
we would love to find methods which are marked as `@api` but are no longer used in any of the comsuming repos of our internal library repositories.

I am thinking about dumping collector call-site data into a file and process such dumped files with the rules.
this would allow me to combine the call-site data of several repositories and use it to feed the rules detect unused methods, even across repositories.

would this be something you are interessted in?

**Comment by TomasVotruba** [comment]
I think this is different use case and better fits for a standalone project that can build on this one :)
This package only deals with current project and I want to keep it that way.
