### ISSUE TITLE
ignore tests

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/unused-public#138]
would you accept a PR adding a new config option which allows to don't report methods unused, when used from tests?

**Comment by staabm** [comment]
alternatively it could make sense to ignore methods which are tagged `@internal` - meaning a method is pubilc because it is public for testing purposes, but not intended for use outside tests

**Comment by TomasVotruba** [comment]
Methods used only in test should be reported.
Same way unused internal methods as designed to be used only in current scope but never used.

On the other hand, methods marked with `@api` are designed to be used externally and in other projects and skipped.

**Comment by staabm** [comment]
Turning this thing differenty: what would you think of using a different error message for methods only used in tests?

That way we would provide better DX (because more precise error message) and also it would be possible to use different ignore rules for the 2 cases..?
