### ISSUE TITLE
detect unused protected properties

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/unused-public#49]
I guess we should be able to detect unused protected properties for classes declared `final`

https://phpstan.org/r/40993704-8fac-4101-8cc3-1124b92666eb

**Comment by TomasVotruba** [comment]
Sounds good to me :+1:

**Comment by staabm** [comment]
Related discussion 
- https://github.com/phpstan/phpstan/issues/9422
- https://github.com/phpstan/phpstan/issues/4954

**Comment by staabm** [comment]
@TomasVotruba I started to think about implementing unused-protected method detection in a simplified form, as in
- skip everything but final classes
- skip all protected methods which override a methode from a parent class, as this would mean it might get called from the base-class because of inheritance
(as you can see this constraints are similar to those for public methods)

do you think I should add a totally separate new collector/rule for the protected methods, or can the already existing "public*" classes be adjusted to treat non-overridding protected methods from final classes in the same way as a public method?

(e.g. it might make sense to rename `PublicClassMethodCollector` to something like `UnusedMethodCandidateCollector` - this would also reflect the concept better, as the current names are pretty tight to the implementation)

**Comment by staabm** [comment]
hmm the more I think about it, the more I think protected stuff should be separated. a lot of checks we do for public methods don't need to be done for protected ones

**Comment by TomasVotruba** [comment]
On second though, this could lead this package focus astrey. Let's stay with dead public element detection only :+1: 

See https://github.com/TomasVotruba/unused-public/pull/68#issuecomment-1647440756
