### ISSUE TITLE
Detect usages from PhpUnit TestCases

### ISSUE THREAD

**Issue by simPod** [TomasVotruba/unused-public#52]
If I understand correctly, phpunit testcases are ignored. 

However, method calls of classes that are placed in my `tests` dir from within phpunit testcases seems to be ignored as well. Therefore those classes' methods are reported as unused.

Is there a way to work around it?

E.g.

```php
namespace Foo\Bar\Tests;

class X {
    public static function foo() {
    }
}
```

```php
namespace Foo\Bar\Tests;

class MyTest {
    public function testSth() {
        X::foo(); 
    }
}
```

`X::foo` is reported as unused.

**Comment by staabm** [comment]
> Is there a way to work around it?

you can annotate the method (or even the whole class) in question with `@api`

see [README](https://github.com/TomasVotruba/unused-public#skip-public-only-methods)

**Comment by simPod** [comment]
Sure but it's not really anything that should be marked with `@api` (https://docs.phpdoc.org/guide/references/phpdoc/tags/api.html) since those are just some internal helpers for few tests. 

So marking it with `@api` sound like lie, IMO it's better to ignore it via baseline but that's not very elegant either.

**Comment by staabm** [comment]
Yeah thats right. You asked for a work arround ;-)

**Comment by staabm** [comment]
But we can improve to better cover your initial example :-)

**Comment by simPod** [comment]
> Yeah thats right. You asked for a work arround ;-)

You got me here 😅

**Comment by TomasVotruba** [comment]
I'm looking into this...

**Comment by TomasVotruba** [comment]
@simPod  I've just added the test fixture in our sets and it's passing well: https://github.com/TomasVotruba/unused-public/pull/76
Only the really unused static call is reported :heavy_check_mark: 

This means 2 things:

* this case has been covered in past 3 months
* the added test fixture is different than your use case :)

In the latter, please add failing test fixture in our CI or provide a failing test repository with version 0.1.13+. I'll look into that :+1:

**Comment by TomasVotruba** [comment]
I've added simple dummy test run in our CI to be sure: 
https://github.com/TomasVotruba/unused-public/pull/77

And it also detect correctly just 1 static method :heavy_check_mark: 

https://github.com/TomasVotruba/unused-public/actions/runs/5642950988/job/15283826436

![Screenshot from 2023-07-24 11-08-18](https://github.com/TomasVotruba/unused-public/assets/924196/211fff87-acb7-4bd3-8455-035ad2830d84)


<br>

Not neccesary to make a repository, feel free to fork the PR #77 and make it fail with little changes :)
