### ISSUE TITLE
false positve on interface calls

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/unused-public#53]
when a class implements a interface, a method from said interface should not be suggested to be reduced in visibility.
the code needs to implement the interface contract which dictates the visibility

```php

interface CmsUrlProvider
{
    /**
     * @param string $path
     * @return string
     */
    public function publicUrl($path);
}

class UrlProvider implements CmsUrlProvider
{
    public function publicFormatUrl($path, $type): string
    {
        return '';
    }

    public function publicUrl($path): string
    {
        return $this->publicFormatUrl($path, 'lulu');
    }
}

```

false positive

> Public method "publicFormatUrl()" is used only locally and should turned protected/private

**Comment by TomasVotruba** [comment]
(using most test from the other issue :))

I've just added the test fixture in our sets and it's passing well: https://github.com/TomasVotruba/unused-public/pull/78/files#diff-0ce251747344a9d6ffdb9f68688670dd53f3f8836968c94ba7d5f45643732156

Only the method not require by interface is reported :heavy_check_mark: 

This means 2 things:

* this case has been covered in past 3 months
* the added test fixture is different than your use case :)

In the latter, please add failing test fixture in our CI or provide a failing test repository with version 0.1.13+. I'll look into that :+1:
