### ISSUE TITLE
Detecting unused parameter

### ISSUE THREAD

**Issue by gquemener** [TomasVotruba/unused-public#70]
Hello!

I've been playing with your library, and it has discovered quite a big amount of cases on our codebase! Thanks!

I was wondering if the detection of unused method/function argument (in the body of this method/function) could be considered as an addition to this library?
Or is it out of scope?

Let me show you an example to illustrate: https://phpstan.org/r/d7b91f7c-9bfe-4ea3-b6cf-2a89d34e05a7 (here the `$uppercased` argument would be detected as unused).

I'd be happy to work on a patch if that's so.

**Comment by TomasVotruba** [comment]
Hello,

thanks for such a positive feedback. Glad it's finding places to delete :)


As for unused parameter, this is possible, yet it might require adding a lot of complexity and custom node colletors. You'd have to look for:

* calls, static and method calls
* parameters and flow of control
* references usages of parameter
* magic usage like compact(), $$named variables etc.

This package is at it's limit and I'd prefer to have another package to handle other "unused something" elements, so they're easy to understand by users and maintain by us.

Like unused classes package I published this week :) 
https://github.com/tomasVotruba/class-leak

Could you make a package on your own to handle that? I'd love to try it :+1:

**Comment by gquemener** [comment]
Thanks for your quick response. I'll let you know when I have something tangible (might take some time while I get familiar with phpstan extension point) :+1:
