### ISSUE TITLE
tests folder is missing = does not work without phpstan extensions installer

### ISSUE THREAD

**Issue by techi602** [TomasVotruba/unused-public#8]
I have issue with extension installer not working correctly on my project, therefore I include your extension directly using

```
includes:
	- phpstan-rules.neon
	- data/vendor/tomasvotruba/unused-public/phpstan.neon

```

but then I get error

```

Note: Using configuration file dev\phpstan.neon.
Path dev\vendor\tomasvotruba\unused-public\tests does not exist
```

Creating the tests folder fixes the issue. 

Can you create empty folder? So I wont have to fork it :)

**Comment by TomasVotruba** [comment]
Where is the `tests` directory coming from?

**Comment by techi602** [comment]
I have no idea. Some phpstan code must check if it exists before it loads your extension.

**Comment by TomasVotruba** [comment]
We'll need a reproducible repository for this one.

**Comment by TomasVotruba** [comment]
Closing as reproducer is missing and possibly outdated.

**Comment by techi602** [comment]
Yeah, I have managed to avoid this issue with updated version of phpstan or something
