### ISSUE TITLE
Accidental tag

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/unused-public#83]
Please remove this tag :)

https://github.com/TomasVotruba/unused-public/releases/tag/%24%7BGITHUB_REF%23refs%2Ftags%2F%7D.72

🛰️

**Comment by TomasVotruba** [comment]
How did you find that? 👯

**Comment by szepeviktor** [comment]
Viktor has laser eyes 👁️
But I am blind to achieving business goals.
So we see two different worlds!
